# Generated by Django 2.1 on 2018-08-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_uploaded_unix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='date_uploaded_unix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='peers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='seeds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='size_bytes',
            field=models.IntegerField(default=0),
        ),
    ]
