# Generated by Django 2.1 on 2018-08-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180829_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='status',
            new_name='state',
        ),
    ]
