# Generated by Django 2.1 on 2018-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180829_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
